domain: Agreement
spring:
  application:
     name: AgreementServicemock
  datasource:
        url: jdbc:oracle:thin:@C-MNT-DEVORA01:1521:MNTDEV1
        username: DEAL_OWNER
        password: P0l0mint
        driver-class-name: oracle.jdbc.driver.OracleDriver
        tomcat:
           max-active: 100
           jmx-enabled: true
           max-idle: 5
           min-idle: 2
           min-evictable-idle-time-millis: 60000
           connectionProperties: v$session.program=${domain}_${spring.application.name}
  jpa:
       show-sql: false 
       properties:
          hibernate:
            format-sql: true
            dialect: org.hibernate.dialect.Oracle12cDialect 
---
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-linsbx:1111/eureka,http://cft-v-mt-linsbx:1112/eureka 