eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-intsr1:1111/eureka,http://cft-v-mt-intsr1:1112/eureka
spring:  
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false           

agrPricingAudienceDomainServiceUrl: http://AgrpricingAudienceDomainService
bpgServiceUrl: http://BPGService
agreementServiceUrl: http://AgreementService
audienceDomainServiceUrl: http://AudienceDomainService
revenueSetDomainServiceUrl: http://REVENUESETAPISERVICE
channelDomainServiceUrl: http://CHANNELSDOMAINSERVICE
agrPricingAudienceBusinessServiceUrl: http://AGRPRICINGAUDIENCEBUSINESSSERVICE               