spring:
  datasource:
        url: jdbc:oracle:thin:@C-MNT-DEVORA01:1521:MNTDEV1
        username: APP_OWNER
        password: P0l0mint
        driver-class-name: oracle.jdbc.driver.OracleDriver
        jmx-enabled: true
        tomcat:
            max-active: 100
            jmx-enabled: true
            max-idle: 5
            min-idle: 2
            min-evictable-idle-time-millis: 60000
  jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.Oracle12cDialect

#spring:
#  datasource:
#        url: jdbc:oracle:thin:@C-MNT-TSTORA01:1521:MNTTST1
#        username: MINT_USER
#        password: M1ntT3stU
#        driver-class-name: oracle.jdbc.driver.OracleDriver
#  jpa:
#        properties:
#          hibernate:
#            dialect: org.hibernate.dialect.Oracle12cDialect
             
---
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-linsbx:1111/eureka,http://cft-v-mt-linsbx:1112/eureka
---
mint:
  retry:
     initialInterval: 500
     maxInterval: 20000
     multiplier: 1.5
     maxattempts: 3
---
cariaApprovalUri : http://APPROVALSETUP
serviceBaseURI: http://COMPANYDAOSERVICE
cariaMappingUri: http://CARIAAPPROVALMAPSERVICE/approvals/
companyServiceURI: http://COMPANYSERVICE/company/
productServiceURI: http://PRODUCT-SERVICE-MINT/products
productDAOServiceURI: http://PRODUCT-DAO-SERVICE-MINT/products
approvalValidationServiceUri: http://APPROVALVALIDATIONSERVICE/approvals/ 
url: http://Approval-View-Service-Mint/CampaignApprovals
approvalHistoryUri: http://Approval-View-Service-Mint-ApprovalHistory/approvals/history/
approvalHtml : http://Approval-View-Service-Mint-Html/approvals
vldtRefType: http://CariaApprovalMapService


# For Query Validation Dao Remote Service
com.channel4.mint.queryValidationDaoServerHost: http://QueryApprovalDAOService
com.channel4.mint.queryValidationDaoGetCampaignApproval: /approvals/
com.channel4.mint.approvalvalidation.queryValidationDao.campaignNotFoundMsg: Campaign Approval Details Not Found
com.channel4.mint.queryValidationDaoGetCampaignApprovalList: /approvals?search=approvalNumber[eq]

# For Approval Validation Dao Remote Service
com.channel4.mint.approvalValidationDaoServerHost: http://APPROVALVALIDATIONDAOSERVICE
com.channel4.mint.approvalValidationDaoGetCampaignApproval: /approvals/

prdAdvLnkExist: http://Product-Service-Mint
company.service: http://CompanyService
vldtAudienc: http://AUDIENCEVIEW
com.channel4.mint.cri.queryApprovalDaoCampaignApprovalList: http://QueryApprovalDAOService/approvals?search=approvalNumber[eq]

# For QPS
com.channel4.mint.qps.externalasset.externalAssetHost: http://appservice.int.channel4.local:9138/adsales/qpsexternalassetservice/api
com.channel4.mint.qps.pirate.pirateHost: http://appservice.int.channel4.local:9137/adsales/qpspirateservice/api
com.channel4.mint.qps.singleschedule.singleScheduleHost: http://appservice.int.channel4.local:9136/adsales/qpssinglescheduleservice/api
com.channel4.mint.qps.programScheduleDomain.programScheduleDomainServiceHost: http://QPS-ProgramScheduleDomainService