spring:
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-testsr1:1111/eureka,http://cft-v-mt-testsr2:1112/eureka

url: http://QueryApprovalDAOService/approvals
k2ApprovalViewDetailsUrl : http://k2-server-test02:8020/api/ApprovalTaskList
portfoliosUrl : http://TEAMSERVICE/