eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-uatsr1:1111/eureka,http://cft-v-mt-uatsr2:1112/eureka
           
spring:
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
          
approvalBusinessService : http://ApprovalBusinessService-V1
assignTaskURI: http://k2-server-test03:8020/Approval/ActionTask?
assigneeURI: http://k2-server-test03/Approval/TaskCount?PortfolioId=
k2RedirectURI: http://k2-server-test03:8020/api/RedirectTask?
approvalMappingK2Uri: http://k2-server-test03:8020/api/ApprovalWorkList?
companyServiceURI: http://COMPANYSERVICE/company/
productServiceURI: http://PRODUCT-SERVICE-MINT/products
k2workFlowDomain: channel4
k2workFlowEnv: k2-server-test03
k2workFlowPassword: Password1
k2workFlowUser: SVCK2MINTMULEUSER