eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-intsr1:1111/eureka,http://cft-v-mt-intsr1:1112/eureka
           
spring:
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false           
           
approvalBusinessService : http://ApprovalBusinessService-V1
assignTaskURI: http://k2-server-int02:8020/approval//ActionTask?
assigneeURI: http://k2-server-int02:8020/approval//TaskCount?PortfolioId=
k2RedirectURI: http://k2-server-int02:8020/approval//RedirectTask?
approvalMappingK2Uri: http://k2-server-int02:8020/approval//TaskList?
companyServiceURI: http://COMPANYSERVICE/company/
productServiceURI: http://PRODUCT-SERVICE-MINT/products
k2workFlowDomain: channel4
k2workFlowEnv: k2-workspace-int02
k2workFlowPassword: August@15
k2workFlowUser: mintuser1