spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-linsbx:1111/eureka,http://cft-v-mt-linsbx:1112/eureka
           
approvalsUrl: http://approvalSetup/approvals
audiencelistUrl: http://AudienceDomainService/audiencelist
audienceUrl: http://AudienceDomainService/audience
audiencesUrl: http://AudienceDomainService/audiences
audienceDomainUrl: http://AudienceDomainService
channelSetTxLevelUrl: http://ChannelsDomainService/txlevels
agreementBusinessServiceUrl: http://AGREEMENTBUSINESSSERVICE
audienceDetailServiceUrl: http://AUDIENCEDETAILSERVICE