eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-testsr1:1111/eureka,http://cft-v-mt-testsr2:1112/eureka
           
spring:
  datasource:
        url: jdbc:oracle:thin:@C-MNT-TSTORA01:1521:MNTCT1A
        username: MINT_USER
        password: M1ntT3stU
        driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.Oracle12cDialect           