domain: Delivery
spring:
  
  datasource:
        url: jdbc:oracle:thin:@C-MNT-TSTORA01:1521:MNTCT1A
        username: DEL_USER
        password: DelT3stU
        driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
       show-sql: false 
       properties:
          hibernate:
            format-sql: true
            dialect: org.hibernate.dialect.Oracle12cDialect
            tomcat: 
            connectionProperties: v$session.program=${domain}_${spring.application.name}
---
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-testsr1:1111/eureka,http://cft-v-mt-testsr2:1112/eureka