eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-uatsr1:1111/eureka,http://cft-v-mt-uatsr2:1112/eureka

spring:
  datasource:
        url: jdbc:Oracle:thin:@C-MNT-TSTORA01:1521:MNTUAT1
        username: APP_USER
        password: Mint03s
        driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.Oracle12cDialect           