eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-testsr1:1111/eureka,http://cft-v-mt-testsr2:1112/eureka
    
domain: Commodity          
spring:
  datasource:
        url: jdbc:oracle:thin:@C-MNT-TSTORA01:1521:MNTCT1A
        username: COM_USER
        password: ComT3stU
        driver-class-name: oracle.jdbc.driver.OracleDriver
        tomcat:
            connectionProperties: v$session.program=${domain}_${spring.application.name}
  jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.Oracle12cDialect

commodityGroup: CGR
commoditySubGroup: CSG
commodity: COM
product: PRD
advertiser: ADV