spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://cft-v-mt-uatsr1:1111/eureka,http://cft-v-mt-uatsr2:1112/eureka
           
commodityDomainUrl: http://CommodityDomainService
productdomainUrl: http://PRODUCTDOMAINSERVICE
customProgrammeGroupDomainUrl: http://CPGDOMAINSERVICE
copyBusinessServiceUrl: http://COPYBUSINESSSERVICE
pirateMuleService: http://appservice.test.channel4.local:9942/inventory
qpsPirateMuleService: http://appservice.test.channel4.local:9937/adsales/qpspirateservice/api