spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://cft-v-mt-uatsr1:1111/eureka,http://cft-v-mt-uatsr2:1112/eureka
           
channelDomainServiceUrl: http://ChannelsDomainService
qpsjunctionbusinessserviceUrl: http://QpsJunctionBusinessService
airtimeStatusDomainServiceUrl: http://AirtimeStatusDomainService
agrpricingAudienceDomainService: http://AgrpricingAudienceDomainService
audienceDomainService : http://AUDIENCEDOMAINSERVICE
networkLevelTxId: 0
scheduleGroupTypeLFTBreak: test
eventTypeSpot: SPOT
eventTypeSFT: SFTSPOT
eventTypeId : 5
thresholdMinEfficiency: 0
commercialBreakDomainUrl: http://CommercialBreakDomainService
programmescheduledomainservice: http://QPS-ProgramScheduleDomainService
regionDomainServiceUrl : http://RegionDomainService
maintaintrailslottBusinessService : http://MaintainTrailslotBusinessService
commodityDomainService : http://CommodityDomainService
trailDomainService : http://TrailDomainService
trailCopyDomainService : http://TrailCopyDomainService
productDomainService : http://Product-DAO-Service-Mint
commercialInventoryDomainService : http://CommercialInventoryDomainService
commercialInventoryBusiness : http://CommercialInventoryBusinessService
singleScheduleURL : http://appservice.test.channel4.local:9951/delivery/api
com.channel4.mint.qps.externalasset.externalAssetHost: http://appservice.test.channel4.local:9938/adsales/qpsexternalassetservice/api
com.channel4.mint.qps.pirate.pirateHost: http://appservice.test.channel4.local:9937/adsales/qpspirateservice/api
com.channel4.mint.qps.singleschedule.singleScheduleHost: http://appservice.test.channel4.local:9936/adsales/qpssinglescheduleservice/api
com.channel4.mint.qps.programScheduleDomain.programScheduleDomainServiceHost: http://QPS-ProgramScheduleDomainService
com.channel4.mint.qps.junction.audienceHost: http://AUDIENCEVIEW
com.channel4.mint.qps.programScheduleDomain.efficiencyDomainServiceHost: http://Qps-EfficiencyTargetDomainService  

com.channel4.mint.qps.scheduleValue: schedule
com.channel4.mint.qps.uktv: Uk Tv
com.channel4.mint.qps.scheduleGroupChannelType: Channel
com.channel4.mint.qps.scheduleGroupProgramme: PROGRAMME  
com.channel4.mint.qps.scheduleGroupCommercial: COMMERCIAL
com.channel4.mint.qps.dateFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
com.channel4.mint.qps.defaultStartTime: 00:00:00
com.channel4.mint.qps.defaultEndTime: "23:59:59"
com.channel4.mint.qps.dataFormatOutput: yyyy-MM-dd
com.channel4.mint.qps.timeFormat: HH:mm:ss
# In Hour
com.channel4.mint.qps.specificJunctionIntervalInHour: 1
# Three Minutes
com.channel4.mint.qps.nearestJunctionInSeconds: 180


distributionType: CHANNEL
scheduleGroupCommercialTypeId: 3
scheduleEventTrailTypeId: 9
scheduleGroupCommercialType: COMMERCIAL
createScheduleGroupPirateUrl: http://appservice.test.channel4.local:9942/inventory/singleSchedule/createschedulegroup
modifyScheduleGroupPirateUrl: http://appservice.test.channel4.local:9942/inventory/singleSchedule/modifyschedulegroup
deleteScheduleGroupPirateUrl: http://appservice.test.channel4.local:9942/inventory/singleSchedule/deleteScheduleGroups
com.channel4.mint.qps.singleschedule.singleScheduleHostTemp: http://appservice.int.channel4.local:9942/inventory/getsingleschedulegroup
com.channel4.mint.qps.singleschedule.eventTypeHost: http://appservice.test.channel4.local:9942
commercialbreakStartTimeFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
commercialBreak: COMMERCIAL
lftBreakType: LFTELESHOPPINGBREAK
commercialBreakBusinessUrl: http://COMMERCIALBREAKBUSINESSSERVICE
threadCount: 10
sftslConstant: 30000
planned: PLANNED
isRatingRequired: ISRATINGREQUIRED
aiRTimeStatus: AIRTIMESTATUS
hiddenToSales: Hidden to Sales
sfTeleshoppingSL: SFTELESHOPPINGSL
bseTime: "30:59:59"
bstTime: "28:59:59"
otherTime: "29:59:59"
spotSL: SPOTSL