eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-testsr1:1111/eureka,http://cft-v-mt-testsr2:1112/eureka
---
domain: Campaign
spring:
  datasource:
        url: jdbc:oracle:thin:@C-MNT-TSTORA01:1521:MNTCT1A
        username: CAM_USER
        password: CAM_USER
        driver-class-name: oracle.jdbc.driver.OracleDriver
        tomcat:
         connectionProperties: v$session.program=${domain}_${spring.application.name}
  jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.Oracle12cDialect

defaultPage : 0
defaultcount : 100

com.channel4.mint.cri.cariaMappingUrl: http://CariaApprovalMapService
com.channel4.mint.cri.onhold: On-Hold
com.channel4.mint.cri.readyForProcessing: Ready to Process
com.channel4.mint.cri.readyForProcessingWarn: Ready to Process - Warning
com.channel4.mint.cri.queryApprovalDaoCampaignApprovalList: http://QueryApprovalDAOService/approvals?search=approvalNumber[eq]