spring:
  datasource:
    url: jdbc:oracle:thin:@C-MNT-DEVORA01:1521:MNTDEV1
    username: FWCONFIG
    password: l0llip0p
    driver-class-name: oracle.jdbc.driver.OracleDriver
    jmx-enabled: true
    tomcat:
        max-active: 100
        jmx-enabled: true
        max-idle: 5
        min-idle: 2
        min-evictable-idle-time-millis: 60000
    
  jpa:
    show-sql: false
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://cft-v-mt-intsr1:1111/eureka,http://cft-v-mt-intsr1:1112/eureka