spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://cft-v-mt-uatsr1:1111/eureka,http://cft-v-mt-uatsr2:1112/eureka
           
destinationQueue: 
activeMQUrl: tcp://fcr-v-esbtest01:61629
activeMqUser: salesmquser
activeMqPassword: 7oXlgP4NcgsaDY
corePoolSize : 70
maxPoolSize : 100
queueCapacity : 400000
fixedRate : 100000
sucessMsg : Success
failureMsg: failure
promotionInventoryDomainServiceURL: http://PromoInvCalculationsDomainService-V1
inventoryDomainServiceURL : http://INVENTORYDOMAINSERVICE-V1
inventoryBusinessServiceURL : http://INVENTORYBUSINESSSERVICE-V1
inventoryQueue : T_INVP
fixedRateJMS : 10000
muleExchangeRateServiceUrl: http://appservice.test.channel4.local:9945/forecast/api
campaignDomainUrl: http://CAMPAIGNDOMAINSERVICE-V1