spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-uatsr1:1111/eureka,http://cft-v-mt-uatsr2:1112/eureka
       
promocampaignDomainUrl: http://PROMOTIONCAMPAIGNDOMAINSERVICE
onlinepackageDomainUrl: http://ONLINEPACKAGEDOMAINSERVICE
promocampaignBussinessUrl : http://PROMOTIONCAMPAIGNBUSINESSSERVICE
teamDaoServiceUrl: http://TEAMDAOSERVICE
qpsScheduleEpisodeService: http://QPSSCHEDULEEPISODESERVICE
promoStrategyDomainUrl: http://MAINTAINPROMOTIONSTRATEGYDOMAINSERVICE
promoCampaignRoleName: UR_MediaPlanningManager
platformDomainUrl: http://PlatformDomainService