spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-linsbx:1111/eureka,http://cft-v-mt-linsbx:1112/eureka
           
episodesCertificateDetailsUrl: http://QpsScheduleEpisodeService/scheduledepisodes
programScheduleDomain : http://QPS-ProgramScheduleDomainService
programScheduleBusiness: http://QPS-PROGRAMMESCHEDULEBUSINESSSERVICE
scheduledEpisodeService: http://QpsScheduleEpisodeService
inventoryDomainService: http://InventoryDomainService-V1
inventoryBusinessService: http://InventoryBusinessService-V1