spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-linsbx:1111/eureka,http://cft-v-mt-linsbx:1112/eureka
           
efficiencyTargetsUrl: http://Qps-EfficiencyTargetDomainService/efficiencytargets
efficiencyTargetsUrlUpdated: http://Qps-EfficiencyTargetDomainService/channels
channelDomainService: http://ChannelsDomainService