eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-uatsr1:1111/eureka,http://cft-v-mt-uatsr2:1112/eureka
---
spring:
  jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: false


com.channel4.mint.qps.externalasset.externalAssetHost: http://appservice.test.channel4.local:9938/adsales/qpsexternalassetservice/api
com.channel4.mint.qps.pirate.pirateHost: http://appservice.test.channel4.local:9937/adsales/qpspirateservice/api
com.channel4.mint.qps.singleschedule.singleScheduleHost: http://appservice.test.channel4.local:9936/adsales/qpssinglescheduleservice/api
com.channel4.mint.qps.programScheduleDomain.programScheduleDomainServiceHost: http://QPS-ProgramScheduleDomainService
com.channel4.mint.qps.junction.audienceHost: http://AUDIENCEVIEW
com.channel4.mint.qps.programScheduleDomain.efficiencyDomainServiceHost: http://Qps-EfficiencyTargetDomainService  

com.channel4.mint.qps.scheduleValue: schedule
com.channel4.mint.qps.uktv: Uk Tv
com.channel4.mint.qps.scheduleGroupChannelType: Channel
com.channel4.mint.qps.scheduleGroupProgramme: PROGRAMME  
com.channel4.mint.qps.scheduleGroupCommercial: COMMERCIAL
com.channel4.mint.qps.dateFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
com.channel4.mint.qps.defaultStartTime: 00:00:00
com.channel4.mint.qps.defaultEndTime: "23:59:59"
com.channel4.mint.qps.dataFormatOutput: yyyy-MM-dd
com.channel4.mint.qps.timeFormat: HH:mm:ss
# In Hour
com.channel4.mint.qps.specificJunctionIntervalInHour: 1
# Three Minutes
com.channel4.mint.qps.nearestJunctionInSeconds: 180


distributionType: CHANNEL
scheduleGroupCommercialTypeId: 3
scheduleGroupCommercialType: COMMERCIAL
createScheduleGroupPirateUrl: http://appservice.test.channel4.local:9942/inventory/singleSchedule/createschedulegroup
modifyScheduleGroupPirateUrl: http://appservice.test.channel4.local:9942/inventory/singleSchedule/modifyschedulegroup
deleteScheduleGroupPirateUrl: http://appservice.test.channel4.local:9942/inventory/singleSchedule/deleteScheduleGroups
channelDomainServiceUrl : http://ChannelsDomainService
regionDomainServiceUrl : http://RegionDomainService
com.channel4.mint.qps.singleschedule.singleScheduleHostTemp: http://appservice.test.channel4.local:9942/inventory/getsingleschedulegroup
com.channel4.mint.qps.singleschedule.eventTypeHost: http://appservice.test.channel4.local:9942
scheduleModeDomainService : http://QpsScheduleModeDomainService