eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-uatsr1:1111/eureka,http://cft-v-mt-uatsr2:1112/eureka
---
spring:
  jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: false

# Single quoted word will not be parsed, It will treat as String            
com.channel4.mint.qps.service.scheduleMode.scheduler: '0 0 0 * * WED'
com.channel4.mint.qps.scheduleModeHost: http://QpsScheduleModeDomain