eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-linsbx:1111/eureka, http://cft-v-mt-linsbx:1112/eureka
---
spring:
  jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.Oracle12cDialect
            

com.channel4.mint.qps.externalasset.externalAssetHost: http://appservice.int.channel4.local:9138/adsales/qpsexternalassetservice/api
com.channel4.mint.qps.pirate.pirateHost: http://appservice.int.channel4.local:9137/adsales/qpspirateservice/api
com.channel4.mint.qps.singleschedule.singleScheduleHost: http://appservice.int.channel4.local:9136/adsales/qpssinglescheduleservice/api
com.channel4.mint.qps.programScheduleDomain.programScheduleDomainServiceHost: http://QPS-ProgramScheduleDomainService
channelDomainServiceUrl : http://CHANNELSDOMAINSERVICE
scheduleModeDomainUrl : http://QPSSCHEDULEMODEDOMAINSERVICE
assetBusinessService : http://AssetBusinessService
com.channel4.mint.qps.scheduleValue: schedule
com.channel4.mint.qps.uktv: Uk Tv
com.channel4.mint.qps.scheduleGroupChannelType: Channel
com.channel4.mint.qps.scheduleGroupProgramme: PROGRAMME  
com.channel4.mint.qps.scheduleGroupCommercial: COMMERCIAL
com.channel4.mint.qps.dateFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
com.channel4.mint.qps.defaultStartTime: 00:00:00
com.channel4.mint.qps.defaultEndTime: 29:59:59
com.channel4.mint.qps.dataFormatOutput: yyyy-MM-dd
com.channel4.mint.qps.timeFormat: HH:mm:dd