eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-testsr1:1111/eureka,http://cft-v-mt-testsr1:1112/eureka
---
domain: Inventory
spring:
  datasource:
        url: jdbc:Oracle:thin:@C-MNT-TSTORA01:1521:MNTCT1A
        username: INV_USER
        password: InvT3stU
        driver-class-name: oracle.jdbc.driver.OracleDriver
        tomcat:
            connectionProperties: v$session.program=${domain}_${spring.application.name}
  jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.Oracle12cDialect
---
dateFormatRegex : ((19|20)\\\d\\\d)(0?[1-9]|1[012])(0?[1-9]|[12][0-9]|3[01])
channelSetUrl: http://ChannelsDomainService/channelsetshierarchy