eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-uatsr1:1111/eureka,http://cft-v-mt-uatsr2:1112/eureka
---
spring:
  datasource:
        url: jdbc:Oracle:thin:@C-MNT-TSTORA01:1521:MNTUAT1            
        username: INV_USER
        password: Mint03s
        driver-class-name: oracle.jdbc.driver.OracleDriver
  jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.Oracle12cDialect

    
            
activeMQUrl: tcp://fcr-v-esbtest01:61629
activeMqUser: salesmquser
activeMqPassword: 7oXlgP4NcgsaDY
sourceQueue: CanonicalTranslator.Q
destinationQueue: BreakAverageRatings.Q
channelSetUrl: http://CHANNELSDOMAINSERVICE/channelsetshierarchy
universeRowCount: 50
threadCount: 40
timeSlice: 1
mediaClockStartTime: '0600'
mediaClockEndTime: '2959'
deleteRecordCount: 10000
ratingOutQueue : T_OUT_RATING