eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-testsr1:1111/eureka,http://cft-v-mt-testsr2:1112/eureka
---
domain: Agreement 
spring:
  datasource:
        url: jdbc:oracle:thin:@C-MNT-TSTORA01:1521:MNTCT1A
        username: DEAL_OWNER
        password: DealT3stO
        driver-class-name: oracle.jdbc.driver.OracleDriver
        tomcat:
            connectionProperties: v$session.program=${domain}_${spring.application.name}
  jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect

yearMaxValue : 2030
versionStart : 1