eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://cft-v-mt-uatsr1:1111/eureka,http://cft-v-mt-uatsr2:1112/eureka
spring:
  datasource:
    url: jdbc:Oracle:thin:@C-MNT-TSTORA01:1521:MNTUAT1
    username: APP_USER
    password: Mint03s
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
serverListAD: DCR-DC04,CFT-DC05,DCR-V-DC06,CFT-V-DC07
serverPortAD: 389
serverRootDN: /DC=CHANNEL4,DC=LOCAL
serverOU: OU=Users,OU=Business
domainName: channel4.co.uk
ldapUserName: mintuser1
ldapPassword: Channel17
searchQueryString: OU=AdSalesRole, OU=Application, OU=User Roles, OU=Business, DC=channel4, DC=local
userManagementDomainUrl: http://userManagementDomainservice