spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
           defaultZone: http://cft-v-mt-testsr1:1111/eureka,http://cft-v-mt-testsr2:1112/eureka
           
commodityDomainUrl: http://COMMODITYDOMAINSERVICE
agreementService: http://AGREEMENTSERVICE
audienceDomainService: http://AUDIENCEDOMAINSERVICE
channelsDomainService: http://CHANNELSDOMAINSERVICE
commercialBreakBusinessUrl: http://COMMERCIALBREAKBUSINESSSERVICE
commercialBreakDomainUrl: http://COMMERCIALBREAKDOMAINSERVICE