spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://cft-v-mt-intsr1:1111/eureka,http://cft-v-mt-intsr1:1112/eureka
           
trailSetDomainService: http://TrailSetDomainService
promoCampaignsBusinessService: http://PromotionCampaignBusinessServiceV1
promoCampaignsDomainService: http://PromotionCampaignDomainServiceV1
productDomainService: http://ProductDomainService