server:
   port: 1111
eureka:
   instance:
      hostname: peer1
   client:
      serviceUrl:

           defaultZone: http://localhost:1112/eureka/
       
local:
    server:
       port : 1111    
logging:
    level:
        org.springframework.web: 'DEBUG'           